# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FJcrWJsXYaWs0_QhJeqtsVO7SBFzH6Qw
"""

from google import genai
from google.genai import types

# Put your API key directly inside the Client definition
client = genai.Client(api_key="AQ.Ab8RN6JqVDG7R-mCU2GRTUPx7MBBU3jLsFxI1HqD2_NEsdhW2Q")

prompt = input("Enter Prompt: ")

response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents=prompt,
    config=types.GenerateContentConfig(
        max_output_tokens=1000
    )
)

print(response.text)

from transformers import pipeline

from transformers import pipeline

# Load English to French translation model
translator = pipeline(
    "text2text-generation",
    model="Helsinki-NLP/opus-mt-en-fr"
)

# English input
english_text = "Hello, how are you? I am learning NLP."

# Translate
result = translator(english_text)

# Display result
print("English:", english_text)
print("French:", result[0]["generated_text"])

!pip install -q transformers sentencepiece

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "Helsinki-NLP/opus-mt-en-fr"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

english_text = "Hello, how are you? I am learning NLP."

inputs = tokenizer(english_text, return_tensors="pt")

outputs = model.generate(**inputs)

french_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

print("English:", english_text)
print("French:", french_text)

import nltk
from nltk import word_tokenize, pos_tag
from nltk.chunk import RegexpParser
from nltk.corpus import wordnet

# Download required NLTK resources (run once)
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

# Input sentence
sentence = input("Enter a sentence: ")

# Step 1: Tokenization
words = word_tokenize(sentence)

# Step 2: Part-of-Speech Tagging
tagged_words = pos_tag(words)

print("\nPOS Tagged Words:")
print(tagged_words)

# Step 3: Define grammar for Noun Phrase
grammar = r"""
    NP: {<DT>?<JJ.><NN.*>+}
"""

# Create chunk parser
chunk_parser = RegexpParser(grammar)

# Step 4: Parse the sentence
tree = chunk_parser.parse(tagged_words)

print("\nNoun Phrases:")
noun_phrases = []

for subtree in tree.subtrees():
    if subtree.label() == "NP":
        np_words = [word for word, tag in subtree.leaves()]
        noun_phrase = " ".join(np_words)
        noun_phrases.append(np_words)

        print(noun_phrase)

# Step 5: Find meaning using WordNet
print("\nSemantic Analysis:")

for np_words in noun_phrases:

    # Usually the last noun is treated as the head noun
    head_word = np_words[-1]

    synsets = wordnet.synsets(head_word)

    if synsets:
        meaning = synsets[0].definition()

        print("\nNoun Phrase:", " ".join(np_words))
        print("Head Word:", head_word)
        print("Meaning:", meaning)

    else:
        print("\nNoun Phrase:", " ".join(np_words))
        print("Head Word:", head_word)
        print("Meaning: Meaning not found")

